@include('layouts.header')
@include('layouts.slider')
@include('pages.features.category')
@include('pages.features.lawfirms')
@include('pages.features.guest')
@include('pages.features.lawschools')
@include('layouts.footer')
